Repository alma/alma-monthlypayments-magento2, pull requests merged in 2024-09, with the labels that each got.

#194 Fix issue The order confirmation email was sent, but the field email_sent remains NULL
  Helpers/PaymentValidation.php
Labels: type: bugfix

#193 Fix getNameUnsanitizedHtml name override
  view/frontend/web/js/view/summary/item/details-mixin.js
Labels: type: bugfix

#195 Insurance reset widget on qty change
  view/frontend/templates/catalog/product/insurance.phtml
Labels: type: feature

#191 Add signature verification on ipn
  Controller/Payment/Ipn.php
  Test/Unit/Controller/Payment/IpnTest.php
  composer.json
Labels: type: feature

#197 Remove insurance products from active carts when insurance is disabled
  Helpers/InsuranceProductHelper.php
  Helpers/ProductHelper.php
  Helpers/QuoteHelper.php
  Model/Adminhtml/Config/Insurance/ConfigurationSave.php
  Model/Exceptions/AlmaProductException.php
  Test/Unit/Helpers/InsuranceProductHelperTest.php
  Test/Unit/Helpers/ProductHelperTest.php
  Test/Unit/Model/Adminhtml/Config/Insurance/ConfigurationSaveTest.php
  Test/Unit/Observer/ShipmentTrackObserverTest.php
Labels: type: feature

#200 Fix bug cart payment payload creation
  Helpers/OrderHelper.php
  Test/Unit/Helpers/OrderHelperTest.php
Labels: bug, type: feature
