Repository alma/alma-monthlypayments-magento2, pull requests merged in 2024-10, with the labels that each got.

#202 Integrate credit for in page
  Controller/Payment/Pay.php
  Gateway/Config/PaymentPlans/PaymentPlanConfig.php
  Gateway/Request/PaymentDataBuilder.php
  Helpers/PaymentPlansHelper.php
  Test/Unit/Helpers/PaymentPlansHelperTest.php
  view/frontend/web/template/payment/spread.html
Labels: type: feature

#205 Update Aqua workflow with trivy-db fix
  .github/workflows/aqua.yml
Labels: type: security

#206 [DEX-697] Run unit tests and lint in separate jobs
  .github/workflows/ci.yml
  Dockerfile
  Taskfile.yml
  Test/Unit/phpunit.ci.xml
  compose.yml
Labels: type: devx

#208 Multi shipping insurance compatibility
  .github/workflows/aqua.yml
  Block/Cart/Item/Renderer.php
  Observer/CheckoutSubmitAllAfter.php
  Test/Unit/Observer/CheckoutSubmitAllAfterTest.php
Labels: hotfix, type: feature

#209 Change wording for in page configuration
  etc/adminhtml/system.xml
  i18n/de_DE.csv
  i18n/en_US.csv
  i18n/es_ES.csv
  i18n/fr_FR.csv
  i18n/it_IT.csv
  i18n/nl_BE.csv
  i18n/nl_NL.csv
  i18n/pt_PT.csv
Labels: type: feature
