Repository alma/alma-monthlypayments-magento2, pull requests merged in 2024-07, with the labels that each got.

#175 [DEVX] Remove internal changes from changelog
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
Labels: type: devx

#178 [DEVX] Update Slack release message
  .github/renovate.json
  .github/workflows/release-publish.yml
Labels: type: devx

#180 [DEVX] Exclude release PRs from the changelog
  .github/release-drafter.yml
Labels: type: devx

#179 Fix add insurance pop up click event listener only for eligible products
  view/frontend/templates/catalog/product/insurance.phtml
Labels: type: feature

#181 [DEVX] Fix release PR not triggering workflows
  .github/workflows/release-pull-request.yml
Labels: type: devx

#183 Add Ui folder to zip
  scripts/build-dist.sh
Labels: skip-changelog, type: feature
