Repository alma/alma-monthlypayments-magento2, pull requests merged in 2025-01, with the labels that each got.

#224 feat: add CartInitiated notification
  Observer/SalesQuoteSaveAfterObserver.php
  Services/MerchantBusinessService.php
  Test/Unit/Observer/SalesQuoteSaveAfterObserverTest.php
  Test/Unit/Services/MerchantBusinessServiceTest.php
  etc/db_schema.xml
  etc/events.xml
Labels: type: feature

#223 Implement merchant business event
  Helpers/Eligibility.php
  Model/Exceptions/MerchantBusinessServiceException.php
  Observer/SalesOrderInvoicePayObserver.php
  Observer/SalesQuoteSaveAfterObserver.php
  Services/MerchantBusinessService.php
  Test/Unit/Observer/SalesOrderInvoicePayObserverTest.php
  Test/Unit/Observer/SalesQuoteSaveAfterObserverTest.php
  Test/Unit/Services/MerchantBusinessServiceTest.php
  etc/db_schema.xml
  etc/events.xml
Labels: type: feature

#225 Remove transform empty string to null
  Services/MerchantBusinessService.php
  Test/Unit/Services/MerchantBusinessServiceTest.php
Labels: skip-changelog, type: feature

#226 Remove ping to France in Slack release messages
  .github/workflows/release-publish.yml
Labels: type: devx, skip-changelog
