Repository alma/alma-monthlypayments-magento2, pull requests merged in 2025-04, with the labels that each got.

#241 Update Renovate configuration, remove outdated dependabot config
  .github/dependabot.yml
  .github/renovate.json
  .github/renovate.json5
Labels: type: refator

#242 Feature/ecom 2616 ac fix first save for fee plans
  Gateway/Config/Config.php
  Helpers/CollectCmsConfigHelper.php
  Helpers/ConfigHelper.php
  Model/Adminhtml/Config/FeePlansConfigBackendModel.php
  Test/Unit/Helpers/CollectCmsConfigHelperTest.php
  Test/Unit/Helpers/ConfigHelperTest.php
Labels: minor

#243 Revert "Feature/ecom 2616 ac fix first save for fee plans"
  Gateway/Config/Config.php
  Helpers/CollectCmsConfigHelper.php
  Helpers/ConfigHelper.php
  Model/Adminhtml/Config/FeePlansConfigBackendModel.php
  Test/Unit/Helpers/CollectCmsConfigHelperTest.php
  Test/Unit/Helpers/ConfigHelperTest.php
Labels: skip-changelog

#244 fix: first save fee plans config
  Gateway/Config/Config.php
  Helpers/CollectCmsConfigHelper.php
  Helpers/ConfigHelper.php
  Model/Adminhtml/Config/FeePlansConfigBackendModel.php
  Test/Unit/Helpers/CollectCmsConfigHelperTest.php
  Test/Unit/Helpers/ConfigHelperTest.php
Labels: type: feature
