Repository alma/alma-monthlypayments-magento2, pull requests merged in 2025-03, with the labels that each got.

#233 Add stripe to CSP whitelist
  etc/csp_whitelist.xml
Labels: hotfix

#235 feat: update README version compatibility
  README.md
Labels: skip-changelog

#237 Fix csp policy for Adyen and checkout.com
  etc/csp_whitelist.xml
Labels: hotfix, type: feature
